language: go

before_script:
  - go get google.golang.org/grpc
  - go get github.com/golang/protobuf/protoc-gen-go
  - proto/generate_proto.sh

script:
  - go build service/usermanagement/server/main.go