language: go

go:
  - 1.13.x

install:
  - scripts/install_protobuf.sh
  - go get google.golang.org/grpc
  - go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
  - go get github.com/golang/protobuf/protoc-gen-go
  

before_script:
  - proto/generate_proto.sh

script:
  - make all