language: go

go:
  - 1.13.x

install:
  - go get -u google.golang.org/grpc
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - scripts/install_protobuf.sh

before_script:
  - proto/generate_proto.sh

script:
  - make all