// Code generated by go-swagger; DO NOT EDIT.

// Package restapi RoomFlow
//
//  An application to help students locate ideal study space
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/github.com.roomflow.backend.v1+json
//
//  Produces:
//    - application/github.com.roomflow.backend.v1+json
//
// swagger:meta
package restapi
